version: "3.9"

services:
  mymongo:
    image: mongo:latest
    container_name: "mymongo"
    ports:
    - 27017:27017
  productservice:
    image: productservice:1.0
    container_name: productservice
    ports:
    - 9090:8080
    links:
      - mymongo