version: "3.9"

services:
  mymongo:
    image: mongo:latest
    container_name: "mymongo"
    ports:
    - 27017:27017
  eurekaservice:
    image: eureka-server
    container_name: eurekaservice
    ports:
      - 8761:8761
#  cartservice:
#    image: cartservice:1.0
#    container_name: cartservice
#    ports:
#      - 8081:8081
#    links:
#      - mymongo
#  orderservice:
#    image: orderservice:1.0
#    container_name: orderservice
#    ports:
#      - 8082:8082
#    links:
#      - mymongo
  productservice:
    image: productservice:1.0
    container_name: productservice
    ports:
    - 8083:8083
    links:
      - mymongo
#  userservice:
#    image: userservice:1.0
#    container_name: userservice
#    ports:
#      - 8084:8084
#    links:
#      - mymongo